### PR TITLE
add myonlineportal.net plugin

### PR DESCRIPTION
**Pull request by BrainSlayer**
just another one from a ticket. so custom is not required anymore

Signed-off-by: Sebastian Gottschall <s.gottschall@dd-wrt.com>

### CODE REVIEW

**Comment by troglobit** [comment]
You might want to change this --> `Copyright (C) 2013` :smile:

**Comment by BrainSlayer** [comment]
ohm yes. thanks

**Comment by BrainSlayer** [comment]
btw. i may also add some other new plugins. just wrote 2 new 30 minutes ago. i will add them to this commit and change topic

**Comment by troglobit** [comment]
Awesome work on this, thanks!

**Comment by BrainSlayer** [comment]
you where to fast. now i have todo another request for more isp's :-)

**Comment by troglobit** [comment]
Sorry, use the 'draft' state of the PR next time.

**Pull request merged**
