### PR TITLE
Add support for dnspod.cn

### PR DESCRIPTION
**Pull request by ysc3839**
https://www.dnspod.cn (Chinese only)

### CODE REVIEW

**Comment by troglobit** [comment]
Looks good to me.  Maybe remove the Copyright lines in `plugins/dnspod.c` and add yourself instead? :)

**Comment by ysc3839** [comment]
Up to you.

**Comment by troglobit** [comment]
I think it should be your name, I'll fix it after merge.

Thank you for your work! :)

**Comment by ysc3839** [comment]
@troglobit Please also fix cloudxns.c

**Comment by troglobit** [comment]
@ysc3839 Thanks for the heads-up, updated `cloudxns.c` as well! :)

**Pull request merged**
