### PR TITLE
chore: add 'success' as a valid response by default

### PR DESCRIPTION
**Pull request by dgrabla**
This will automatically accept the responses for DNSMadeEasy DDNS service. 
It makes sense to have this word on the list of OK responses so inadyn accepts it out of the box with dnsmadeeasy or other providers.

Related-To: https://dnsmadeeasy.com/technology/dynamic-dns (bottom)

### CODE REVIEW

**Comment by troglobit** [comment]
Looks good.

I'm assuming you're using the custom provider setup, do you think you could provide a configuration sample for dnsmadeeasy to help other users out?  Would be really appreciated.

**Comment by troglobit** [comment]
Awesome, thank you!

**Comment by dgrabla** [comment]
@troglobit thanks

Sorry, I have no clue how to write a plugin, I added an example to the readme. 
I'm not sure if there are other examples somewhere for other providers f this is not a good place please let me know.

**Comment by troglobit** [comment]
That'll do fine, there's the man-page and an examples/ subdirectory.  But just having an example in the README is perfectly fine :-)

**Comment by dgrabla** [comment]
:+1:

**Pull request merged**
