### PR TITLE
Add support for Google Domains DynDns.

### PR DESCRIPTION
**Pull request by jmcmanus**

### CODE REVIEW

**Comment by jmcmanus** [comment]
No problem.

Do you have an idea of when the next release will be? It looks like you have a 2.0 milestone with a config file parsing issue that you're waiting on. Any plans for a release before that? Thanks!

**Comment by troglobit** [comment]
I wasn't planning for one, but there's been a few contributions now, so I may do a release soonish. 

Have been putting off the new .conf parser. Not sure if I should invest time in making it backwards compatible?  The Debian/Ubuntu folk may appreciate that, but it's a lot of work to verify. 

Otoh, I want to finish it as well. So maybe I'll give it a go this weekend! 😎

**Comment by queeup** [comment]
Please keep command line support :)

**Comment by troglobit** [comment]
@queeup Very unlikely, you'll have to stick with the 1.x series then. 😞

This is one of the toughest things to deal with in any software project, compatibility. 😕

The code really needs to be cleaned up and further simplified so others can more easily contribute. Maintaining compatibility with existing config files was my initial plan, but for the command line as well is really difficult while at the same time replacing the home grown spaghetti monster with a standardized file parser library (LibConfuse).

I'm sorry!

**Comment by queeup** [comment]
It's OK. I will adapt my self :) I just try once more to change your mind :)

**Comment by troglobit** [comment]
@queeup :smile: :+1:

**Comment by troglobit** [comment]
@jmcmanus Just released https://github.com/troglobit/inadyn/releases/tag/1.99.13 cheers!

**Pull request merged**
