### PR TITLE
Enhance CloudFlare support

### LINKED ISSUE #323: Cloudflare Proxy support
I would like to use the cloudflare proxy feature. The problem is, that after every IP update the the proxy feature gets disabled and reverts back to 'DNS only'.

This is my current config:
```
provider cloudflare.com {
     username = me@example.com
     password = myAccessToken
     hostname = subdomain.mydomain.com
}
```

### PR DESCRIPTION
**Pull request by ntkme**
- This PR adds two cloudflare options: `ttl` and `proxied`.
- Use `https://1.1.1.1/cdn-cgi/trace` to get current ip address.
- Fix a bug where it will fail to update if there is no existing A/AAAA record.
- Add a few cloudflare examples.
- Updated man page and README for new option and config exampels.

Fixes #323.

### CODE REVIEW

**Comment by troglobit** [comment]
Awesome work, thank you!  Only thing I'd like is for the README and manual page to be updated for the Cloudflare plugin, specifically.  Only updating the examples would be sufficient since no other plugin supports ttl or proxied atm.  Fix that (on the same branch/pull-reqeust is OK) and I'll merge this :smiley::+1:

**Comment by ntkme** [comment]
Thanks for quick response! I added an example, as well as a small note about `proxied` breaking cache.

The way CloudFlare proxied DNS record works is that CloudFlare would create A record point to CloudFlare CDN servers, and their servers will reverse proxy request to the origin server. With `proxied = true`, the resolved DNS A record will never be the origin IP. Therefore the cache always will be broken if `proxied = true`.

**Comment by ntkme** [comment]
Maybe I've misread the code what is cached. Let me double check.

**Comment by ntkme** [comment]
OK. I misunderstood previously. The cache would actual prevent repeated updates with `proxied = true`.

**Comment by ntkme** [comment]
@troglobit Sorry for making the scope of this PR bigger than original. I think it is ready for another review. All 5 commits are independent and can be reviewed separately.

**Comment by troglobit** [comment]
No problem.  Looks good to me, only missing the manual page update. Would be really appreciated if you could complement the example in `man/inadyn.conf.5`, similar to the README update.

**Comment by ntkme** [comment]
Updated man page and README.

Also, added a dual stack `cloudflare-ipv4-ipv6.conf` to demonstrate how to configure both ipv4 and ipv6 ddns at the same time.

**Comment by troglobit** [comment]
Perfect, great job with this, thank you! :heart:

**Pull request merged**
