### PR TITLE
add goip.de provider

### PR DESCRIPTION
**Pull request by BrainSlayer**
not much to comment here. just add quick support for goip.de provider

ipv6 support will follow up later

Signed-off-by: Sebastian Gottschall <s.gottschall@dd-wrt.com>

### CODE REVIEW

**Comment by troglobit** [comment]
Awesome! Would you mind also updating the README.md and inadyn.conf with a tiny example?

**Comment by BrainSlayer** [comment]
ah its simple. username, password, domain. but let me try to change everything you requested

**Comment by BrainSlayer** [comment]
done

**Comment by BrainSlayer** [comment]
just for information. i have more patches in background which will follow up soon to fix issues with freedns.afraid.org

**Comment by troglobit** [comment]
Ah great, thanks for the heads-up!  If you let me know when your patch queue is empty, I can prepare the next release :smiley::+1:

**Comment by BrainSlayer** [comment]
correction. it was about easydns which has a yet not implemented response code

**Pull request merged**
