### PR TITLE
Added porkbun support

### PR DESCRIPTION
**Pull request by stescobedo92**
This pull request aims to adapt Inadyn's code so that it can use the PorkBun API, a dynamic DNS provider. To do this, the following functions have been modified:

- setup: to get zone ID and hostname ID using PorkBun API
- request: to send DNS update request using PorkBun API
- response: to check the PorkBun API response status code
- json_extract: to extract the value of a JSON key from the PorkBun API response

and other functions

A new data structure has also been defined to store the information from PorkBun's dynamic DNS system, and corresponding values have been assigned to the structure's fields.

### CODE REVIEW

**Comment by BrainSlayer** [comment]
> 
../../src/../plugins/porkbun.c: In function 'check_success':
../../src/../plugins/porkbun.c:127:46: error: 'KEY_SUCCESS' undeclared (first use in this function); did you mean 'EXIT_SUCCESS'?
  127 |                 if (jsoneq(json, tokens + i, KEY_SUCCESS) != 0)
      |                                              ^~~~~~~~~~~
      |                                              EXIT_SUCCESS
../../src/../plugins/porkbun.c:127:46: note: each undeclared identifier is reported only once for each function it appears in
../../src/../plugins/porkbun.c: In function 'get_result_value':
../../src/../plugins/porkbun.c:169:13: warning: implicit declaration of function 'check_status' [-Wimplicit-function-declaration]
  169 |         if (check_status(json, tokens, num_tokens) == -1) {
      |             ^~~~~~~~~~~~

**Comment by BrainSlayer** [comment]
check_status function is missing too

**Comment by stescobedo92** [comment]
These are the commits that resolve the issues

- Adding KEY_SUCCESS missing value

- Fixing errors

**Comment by troglobit** [comment]
> check_status function is missing too

Thank you for taking the time to review this! 😃👍

**Comment by troglobit** [comment]
I've authorised the CI suite but it fails because `inadyn -h` now suddenly fails?

**Comment by stescobedo92** [comment]
> I've authorised the CI suite but it fails because `inadyn -h` now suddenly fails?

Yes I have noticed that it fails when you try to access the help

**Comment by troglobit** [comment]
> > I've authorised the CI suite but it fails because `inadyn -h` now suddenly fails?
> 
> 
> 
> Yes I have noticed that it fails when you try to access the help

Do you have any idea why?  Looks like it segfaults. How have you tested these changes?

Also, I noticed you pushed another change to this branch. Do you want to change to a Draft PR?

**Comment by stescobedo92** [comment]
> > > I've authorised the CI suite but it fails because `inadyn -h` now suddenly fails?
> > 
> > 
> > Yes I have noticed that it fails when you try to access the help
> 
> Do you have any idea why? Looks like it segfaults. How have you tested these changes?
> 
> Also, I noticed you pushed another change to this branch. Do you want to change to a Draft PR?

I could check to see what happens if I think you can move the PR to draft until you see what the reason for the error is.

The last changes I added were examples for ipv4 and ipv6

**Comment by stescobedo92** [comment]
> > > > > I've authorised the CI suite but it fails because `inadyn -h` now suddenly fails?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Yes I have noticed that it fails when you try to access the help
> > 
> > 
> > > 
> > 
> > 
> > > Do you have any idea why? Looks like it segfaults. How have you tested these changes?
> > 
> > 
> > > 
> > 
> > 
> > > Also, I noticed you pushed another change to this branch. Do you want to change to a Draft PR?
> > 
> > 
> > I could check to see what happens if I think you can move the PR to draft until you see what the reason for the error is.
> > The last changes I added were examples for ipv4 and ipv6
> 
> My point: a PR is usually not made unless you're done with a change to a project. Your change does not pass a basic test (issuing help) and you keep pushing new changes. So it seems to me (the project maintainer) that you're not ready yet for review or merge.
> 
> Yes, I see what your changes do. Do you plan to make more changes not related to fixing the problem I mentioned? If so, this should be converted to a draft, by you.

Those are the latest changes related to porkbun support

**Comment by BrainSlayer** [comment]
> > > I've authorised the CI suite but it fails because `inadyn -h` now suddenly fails?
> > 
> > 
> > Yes I have noticed that it fails when you try to access the help
> 
> Do you have any idea why? Looks like it segfaults. How have you tested these changes?
> 
> Also, I noticed you pushed another change to this branch. Do you want to change to a Draft PR?

i know the cause of the crash. see my first comment for Makefile.am. this is causing the crash in plugin_unregister. i know its curious. but i tested it. fixing this will avoid the crash

**Comment by stescobedo92** [comment]
> i know the cause of the crash/segfault. see my first comment for Makefile.am. this is causing the crash in plugin_unregister. i know its curious. but i tested it. fixing this will avoid the crash

I already fixed it, but noted that if you look at the Cloudflare plugin, the KEY_SUCCESS macro is used

**Comment by BrainSlayer** [comment]
> > i know the cause of the crash/segfault. see my first comment for Makefile.am. this is causing the crash in plugin_unregister. i know its curious. but i tested it. fixing this will avoid the crash
> 
> I already fixed it, but noted that if you look at the Cloudflare plugin, the KEY_SUCCESS macro is used

i never complained about the use of the macro. i complained that the whole function check_success which made use of this macro was never used. i see you corrected this now in the way i'm thinking its correct

**Comment by BrainSlayer** [comment]
your last fixes are buggy too. the & must be removed. this cannot work. can you please test your code?

../../src/../plugins/porkbun.c:169:49: warning: passing argument 3 of 'check_success' makes integer from pointer without a cast [-Wint-conversion]
  169 |         if (check_success(json, tokens + i + 1, &num_tokens) == -1) {

**Comment by stescobedo92** [comment]
> your last fixes are buggy too. the & must be removed. this cannot work. can you please test your code?
> 
> ../../src/../plugins/porkbun.c:169:49: warning: passing argument 3 of 'check_success' makes integer from pointer without a cast [-Wint-conversion] 169 | if (check_success(json, tokens + i + 1, &num_tokens) == -1) {

Fixed errors with & operator in the call of check_success function

**Comment by BrainSlayer** [comment]
if this code has been  tested and is working fully. i vote for merging. so far i havent seen any testresult or at least a word about that.

**Comment by stescobedo92** [comment]
> if this code has been tested and is working fully. i vote for merging. so far i havent seen any testresult or at least a word about that.

with the latest changes fixed it works completely

**Comment by mindofbeholder** [comment]
It's been a while so hoping to bump this to get it merged.

**Comment by troglobit** [comment]
OK, merging.

**Comment by henfri** [comment]
Hello,

thanks for the support for porkbun.
Unfortunately, it does not seem to work.
The first issue is, that the check-ip server does not seem to exist anymore.
I fixed that by a check-ip command.
But then, I get:
```
inadyn[2754903]: Request:
GET /client/v4/dns/retrieve/x.name HTTP/1.0
Host: api.porkbun.com
User-Agent: inadyn/2.12.0 https://github.com/troglobit/inadyn/issues
Accept: */*
Content-Type: application/json
Content-Length: 21

{"apikey":"hendrik@x.name","secretapikey":"pk1_xxx"}
inadyn[2754903]: Successfully sent HTTPS request!
inadyn[2754903]: Successfully received HTTPS response (1693/8191 bytes)!
inadyn[2754903]: Response:
HTTP/1.1 404 Not Found

```

It is notable, that https://porkbun.com/account/api is refering to API V3. Here, I see no permissions like
permissions: Zone.Zone - Read, Zone.DNS - Edit.

Is there a change to the API?

Best regards,
Hendrik

**Comment by troglobit** [comment]
> Hello,
> 
> 
> 
> thanks for the support for porkbun.
> 
> Unfortunately, it does not seem to work.
> 
> The first issue is, that the check-ip server does not seem to exist anymore.
> 
> I fixed that by a check-ip command.
> 
> But then, I get:
> 
> ```
> 
> inadyn[2754903]: Request:
> 
> GET /client/v4/dns/retrieve/x.name HTTP/1.0
> 
> Host: api.porkbun.com
> 
> User-Agent: inadyn/2.12.0 https://github.com/troglobit/inadyn/issues
> 
> Accept: */*
> 
> Content-Type: application/json
> 
> Content-Length: 21
> 
> 
> 
> {"apikey":"hendrik@x.name","secretapikey":"pk1_xxx"}
> 
> inadyn[2754903]: Successfully sent HTTPS request!
> 
> inadyn[2754903]: Successfully received HTTPS response (1693/8191 bytes)!
> 
> inadyn[2754903]: Response:
> 
> HTTP/1.1 404 Not Found
> 
> 
> 
> ```
> 
> 
> 
> It is notable, that https://porkbun.com/account/api is refering to API V3. Here, I see no permissions like
> 
> permissions: Zone.Zone - Read, Zone.DNS - Edit.
> 
> 
> 
> Is there a change to the API?
> 
> 
> 
> Best regards,
> 
> Hendrik

@henfri this seems pretty bad, my gut reaction is to revert the porkbun support completely so other users don't experience the same issues. What do you think we should do?

**Comment by henfri** [comment]
Lets wait for @stescobedo92 to comment... 
Maybe it is easy to fix

**Comment by lunik1** [comment]
Please also see #483

**Comment by lunik1** [comment]
There has been no response from @stescobedo92, I think this should be reverted?

**Pull request merged**
