### PR TITLE
Distribute and install configuration examples.

### PR DESCRIPTION
**Pull request by acolomb**
This should work as outlined in #187. Missing bits:

* Check Debian installation scripts for needed adjustments.
* ~~Test installation in correct directory with `make distcheck` (so far only verified with `make -n`)~~

### CODE REVIEW

**Comment by acolomb** [comment]
Well, at least the tree output on Travis' build shows the files correctly installed.

**Comment by acolomb** [comment]
I suppose the build failure is exclusively your fault because of changes on the master branch ;-)

`dpkg-buildpackage` works fine for me and produces a package including the examples directory. Just unsure if something needs to be added to `debian/docs`?

**Comment by troglobit** [comment]
Heh, yeah I've been experimenting on master a bit the last hour ;-)

I've added `--ignore-missing-info` to `dpkg-shlibdeps`, seems to work better with Trusty.  You probably need to add `examples/README.md` to `debian/docs`, good catch!

**Comment by acolomb** [comment]
Reading up on https://www.debian.org/doc/manuals/maint-guide/dother.en.html, I think the following files are actually redundant:

* `debian/docs`
* `debian/install`
* `debian/manpages`
* `debian/inadyn.examples` (after moving inadyn.conf to `examples/`)

Should I include that in this PR?

**Comment by troglobit** [comment]
Aha! Yes, please do! :+1:

**Comment by acolomb** [comment]
Done and verified by looking at the result of `dpkg-buildpackage`.

**Comment by troglobit** [comment]
Looks great, as usual! :+1:

**Pull request merged**
