### PR TITLE
List all required permissions for Cloudflare

### PR DESCRIPTION
**Pull request by jorhett**
The instructions provided with the cloudflare example don't work:

```
{"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.*******' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}
```

I believe my changes are an improvement.

Also replaced tabs with spaces.

### CODE REVIEW

**Comment by jorhett** [comment]
@SimonPilkington should see this

**Comment by jorhett** [comment]
I've just changed the text again to address the first problem noted in #286

**Comment by troglobit** [comment]
Good find @jorhett, waiting for @SimonPilkington to weigh in on this one.

**Comment by SimonPilkington** [comment]
Agree with the formatting changes, but where do you need the Account: Account Settings - Read permission? My token works perfectly fine without it.

**Comment by jorhett** [comment]
> but where do you need the Account: Account Settings - Read permission? My token works perfectly fine without it.

I showed you the response I got without it.  Adding it made it work. This is discussed at length here https://community.cloudflare.com/t/bug-zone-detail-by-name-requires-zone-list-permission/128042

**Comment by jorhett** [comment]
I removed the note about pre-create since it has been fixed.

**Comment by SimonPilkington** [comment]
I was able to reproduce the problem after selecting a specific zone as the resource for the token. Please note that it appears to be an API bug in the text.

**Comment by jorhett** [comment]
> I was able to reproduce the problem after selecting a specific zone as the resource for the token. 

Ah, yes. We don't let laptops walk around with api tokens that can modify production cloudflare zones ;-) 

> Please note that it appears to be an API bug in the text.

Not sure what you're saying here.

**Comment by SimonPilkington** [comment]
> Not sure what you're saying here.

I mean add a note in README.MD next to the Account: Account Settings - Read permission saying that it is required to a bug in the API. We should remove it as a requirement if the bug is fixed.

**Comment by jorhett** [comment]
@SimonPilkington is the latest what you want?

**Comment by SimonPilkington** [comment]
That's good. @troglobit, merge whenever you want.

**Pull request merged**
