### PR TITLE
Add support for ddnss.de and (ipv4).dynv6.org

### PR DESCRIPTION
**Pull request by svenhoefer**

### CODE REVIEW

**Comment by troglobit** [comment]
Great stuff! :+1: 

Could you update the README.md and man page(s) as well, that would be awesome!

**Comment by svenhoefer** [comment]
Done.

**Comment by troglobit** [comment]
Good work! :+1: 

I'll rebase, clean up the commit messages a bit, and merge it later this week.

Thank you so much for your contribution to Inadyn! :smiley:

**Comment by svenhoefer** [comment]
Not a problem. ;)

I have two feature-requests too.
1.) Please remove the outdated checks for username and password. Some providers doesn't need this and it isn't nice to define "password = none" in this cases.

2.) Please add the possibility to add a custom response-string to custom providers to avoid commits like https://github.com/svenhoefer/inadyn/commit/7ab906e1759c2b5fb369c235a67ccf8a5de412d6 and avoid the use of --continue-on-error.

Then a cusom provide can looks like this:
custom ddnss.de {
        ssl = true
        ddns-server = ddnss.de
        ddns-path = "/upd.php?key=MYLONGLONGKEY&host="
        alias = myhost.ddnss.de
        response = "Updated"
}

**Comment by troglobit** [comment]
1. By "outdated checks" I'm guessing you mean the config file validator for *custom* providers? If so, then yes, that's a great idea!
2. When I looked at svenhoefer@7ab906e that was exactly what I was thinking as well, thanks!

(For future reference, it's always best to file feature requests as separate issues. Otherwise the maintainer risk forgetting about them)

**Comment by svenhoefer** [comment]
What's the problem, Joachim?

**Comment by troglobit** [comment]
Lack of time, unfortunately. Will hopefully get back to Inadyn soon.

**Comment by troglobit** [comment]
Rebased, squashed a bit, and rewrote log messages to project style.

Merged to master.  Thank you again! :+1:

**Pull request closed without merging**
