### PR TITLE
Fix multiple Debian packaging issues

### PR DESCRIPTION
**Pull request by acolomb**
Most notably, repair the broken binary install location mentioned in #194.  Other fixes are mostly stuff hinted at by a lintian check (Lintian v2.5.55 on my current Ubuntu 17.10 system).

Unfixed lintian warnings:
* Missing translations for Debian templates (see #195)
* `watch` file in a "native" package, but we can safely ignore this.
* ancient-standards-version 3.9.6 (current is 4.1.3).  There's a whole bunch of changes that need investigation before claiming a higher standards version, see e.g. https://www.debian.org/doc/packaging-manuals/upgrading-checklist.txt; too much for this PR.

### CODE REVIEW

**Comment by acolomb** [comment]
Oh crap, lintian's dependency "advice" doesn't seem to be terribly backwards-compatible.  Will look into it tomorrow.

**Comment by troglobit** [comment]
Looks good, except for the last two commits.  I understand the reasoning from lintians perspective, but I'd prefer to use dash in debian packaging versions, to keep the tarball the pristine source.  Shipping .deb files is mostly a convenience, Debian should do the real packaging.  I'd also like to continue creating symlinks in autogen.sh, because when you run `make dist` autotools converts these symlinks to proper files in the resulting archive.

**Comment by acolomb** [comment]
How does the Debian version change what goes into a tarball?  If you mean the source tarball generated by `dpkg-buildpackage`, it's almost identical to the one from `make dist`, plus the `debian/` directory.  As long as you keep that as part of the master branch, the resulting `.deb` file in fact represents the released upstream version.  I was already wondering why you commited the debian/changelog _after_ tagging the release.  In my opinion, it should be treated as part of the release--or we move the Debian scripts to a separate branch with separate releases, abandoning the "native" package approach.  The latter would add much complexity for no apparent benefits.

Regarding the script vs. symlinks: If they are copied by `make dist`, why not also copy them in `autogen.sh`?  Either way the version which ends up there is the one from the local developer machine.  Symlinks would break if you upgrade your local autotools.  Copies just need to be replaced, which I do regularly during testing with `git clean -fdX; ./autogen.sh`.  What's the benefit of symlinking?

Regarding Debian package maintenance, have you contacted @taem about pulling and uploading a more recent release?

**Comment by acolomb** [comment]
I reverted the debhelper change because it won't even work with an alternative spec of `debhelper (>= 9.20160709~) | dh-systemd`.  Switching the order would fix the Travis build, but again triggers the same Lintian warning.

**Comment by troglobit** [comment]
Sorry, was a bit tired when I reviewed the PR. I meant the change to configure.ac: 2.3 --> 2.3.1 instead of 2.3-2.

I've had a policy for all my projects to keep a separate release process for the standard tarballs and the debian packaging.  The latter has mostly been out of convenience for myself, to ease testing on x86. If the two release processes align, then fine, but packaging specifics go into the debian directory, the rest I try to maintain agnostic of Linux distributions. In particular because the main target of my work is non-debian (embedded) targets. I've used native format only to silence the most basic warnings/errors and allow building from the GIT repo. I'd very much prefer if Debian picked up maintenance instead, but I've heard nothing from @taem for a couple of years now, so I've assumed the package was dying in Debian -- that's another reason why I've imported the half-finished debconf work and tried to develop the debian/ bits, to the best of my knowledge, yet keeping it separate (without any extra branches or whatnot). 

Regarding symlinks, that's just another matter of preference for me. I don't like keeping generated files in the repo and having lots of projects using autotools wastes quite a bit of space, again a preference for me.

**Comment by acolomb** [comment]
Okay, I get where you're going with the version number stuff.  Because the changes are only in the debian/ subdir, you don't want to bump the "upstream" version.  I'd recommend treating debian/ as a part of the software, so any changes there result in a changelog entry with the same version as in `configure.ac`.  The other "clean" alternative would be to separate it from the master branch, but I think we agree that it is not worth the trouble.

Having a "native" package should imply two things: The deb version IS the native upstream version and any packaging changes warrant a new release version number. Second, the debian/ subdir is considered part of the package and therefore should also be distributed in release tarballs. My bumping the revision component was to indicate that this is only a maintenance update, and even a no-op for the `make dist` tarball thus far.

My use case for Inadyn is *solely* dependent on the Debian package, to cleanly track installed files on any machine that uses it.  Having the debian build scripts already in the repo was a blessing for me, even better if they lived in the tarball releases as well.  So I'm fine with waiting for the next "upstream" version-bump before these packaging changes end up in a tagged release.  But please remember, every git tag includes *some* version of the packaging scripts, and right now that version is completely broken.

As for the symlinks: even when copied, the autotools scripts *never* end up committed to the repository--but *always* end up in `make dist` as copies.  The problem only arises when `dpkg-buildpackage` rolls its source tarball from a working copy where `autogen.sh` was run, saving the symlinks as such.  I would not hit that problem if it were possible to build the debian package from the pristine `make dist` archives.

If you're worried about space usage, you could do `git clean -fX` when done with a project to save 740 kB :-)

**Comment by troglobit** [comment]
Your reasoning is sound, of course, and exposes a few holes in my own arguments. I'm realizing that my including a `debian/` directory implies to users that they can expect up-to-date and working `.deb`
files as part of a regular release.

The main reason, which I was trying to avoid to tell you, is that accepting the logic of your statements means more work for me as the maintainer, more testing and more things that can block a
release.  Sure that should be a minor hurdle, but when ones time is already limited this is not ideal.

However, I cannot stand being illogical, even when it's with a low-priority project like Inadyn, so we'll do it your way ... :drum:  ... Debian packages are now an official part of releases! :smiley::+1: 

I'm struggling a bit with if `make release` (or `make dist`) should now include the `debian/` directory. (Re: we discussed this previously) But I guess we can wait a bit more to see if we get any [reaction from Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846935).  However, I'm noticing now that it seems [Inadyn has been orphaned](https://packages.qa.debian.org/i/inadyn.html) ... 

I guess I should start writing things like this down, the release process, etc. in a HACKING document, or similar ... oh well.

**Comment by acolomb** [comment]
Thanks for your consideration :-)

**Pull request merged**
