### PR TITLE
openssl library needed to compile on Debian

### PR DESCRIPTION
**Pull request by bashrc**
Add an extra build dependency.

### CODE REVIEW

**Comment by troglobit** [comment]
Nope, that should not be necessary. It should be sufficient to just use GnuTLS, due to the license problems Debian list with OpenSSL.

If you've experienced problems building without OpenSSL I'm very interested in hearing the details about that, and the Debian version+host you're attempting to build on.

**Comment by bashrc** [comment]
If it shouldn't be necessary it currently is to configure on Debian Stretch.

**Comment by troglobit** [comment]
I just tried on one of my Stretch installs, configure works just fine without libssl-dev ... could you please elaborate?

**Comment by bashrc** [comment]
If I just use:

    ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var

Is that still sufficient to enable TLS?

**Comment by troglobit** [comment]
Yep, building with SSL/TLS is the default. To disable you have to `--disable-ssl`.

**Comment by troglobit** [comment]
So, then I guess we can close this PR, right?

**Comment by bashrc** [comment]
Yes

**Pull request closed without merging**
