### PR TITLE
Add support for cloudxns.net

### PR DESCRIPTION
**Pull request by ysc3839**
https://www.cloudxns.net/en/

### CODE REVIEW

**Comment by troglobit** [comment]
Good work! :smiley: 

Just a heads-up for next time: please make sure to follow coding style.  I'll do the changes myself this time, so you can have look at it, but next time I'll likely reject it in the code review.

**Comment by ysc3839** [comment]
Thanks!

**Comment by troglobit** [comment]
Well, `ctime()` does all the things `strftime()` does, but apart from it also adding a `\n` which we then have to account for (remove), it also has some side effects like setting the time zone.

The resulting code after the refactor, using `strftime()`, is formatted just like `ctime()` but without the extra `strdup()` + `free()`, which for an embedded system where Inadyn has its main audience, is important.

I was actually curious why you used `ctime()` to begin with, it formats the time string in a locale dependent way, so it would look different in the U.S., France, or here in Sweden.  Whereas the example in your code used an ISO formatting: "2017-04-08 18:43:57" -- maybe we should use the ISO formatting in `strftime()` instead of the U.S./english `ctime()` variant?

**Comment by ysc3839** [comment]
I use `ctime` because it's simple. The `DATE` required by server is just a random string to make `HMAC` unique.

**Comment by troglobit** [comment]
I see, well since the contents don't matter we can keep the code as is.

**Comment by ysc3839** [comment]
The `http_init` is before `info->system->request` in [src/ddns.c#L543](../blob/3fcc1bd38652fd00ec25f7c6e5f373102c6a3fe2/src/ddns.c#L543). Since there's two http requests in cloudxns.c, I think it may reach timeout. Should we call `http_init` after `request`?

**Comment by troglobit** [comment]
It's a little bit tricky in Inadyn plugins with providers that require you to do some more transactions before actually sending the update.  The FreeDNS plugin does a similar dance and we've never had an issue with that. Also, the timeouts are quite generously set.

So, unless you can see an actual problem, I don't think another `http_init()`, or changing the order of them, is necessary.

Good thinking though! :+1:

**Pull request merged**
