### PR TITLE
Cloudflare: Fix memory leaks when parsing JSON

### PR DESCRIPTION
**Pull request by SimonPilkington**
I've been spending too much time with garbage collectors and RAII after all. Checked all my mallocs now, should be fine.

### CODE REVIEW

**Comment by SimonPilkington** [comment]
I ran the current version through Valgrind to be as safe as possible. Seems good.

**Comment by troglobit** [comment]
Thank you, that was one of the items of my release checklist! <3

**Comment by SimonPilkington** [comment]
> 
> 
> Thank you, that was one of the items of my release checklist! <3

Note that I only ran it with the -1 -n flags and for my own plugin. Other plugins could still potentially be (or become) leaky. It wouldn't be amiss to do more Valgrind runs if you'll be doing work for #254.

**Comment by troglobit** [comment]
OK, thanks!

**Pull request merged**
