### PR TITLE
Support Cloudflare.

### PR DESCRIPTION
**Pull request by SimonPilkington**
Not sure if @SilverBut is still working on this, but since the last post on #208 was nearly a year ago I just went ahead and did it myself.

Comments welcome. I haven't done C in a while.

Changes:
	* Move JSMN implementation to its own file so it can be reused.

Config notes for Cloudflare:
	* Cloudflare separates records by zones; this is currently
handled by making the zone a part of the username.

Cloudflare API docs: https://api.cloudflare.com/

Signed-off-by: SimonP <SimonPilkington@users.noreply.github.com>

### CODE REVIEW

**Comment by troglobit** [comment]
Good work, do you mind fixing the build problem with GCC?

```
../plugins/cloudflare.c: In function ‘check_success’:
../plugins/cloudflare.c:156:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 1; i < num_tokens; i++) {
  ^
../plugins/cloudflare.c:156:2: note: use option -std=c99 or -std=gnu99 to compile your code
../plugins/cloudflare.c: In function ‘get_result_value’:
../plugins/cloudflare.c:202:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 1; i < num_tokens; i++) {
  ^
make[1]: *** [../plugins/inadyn-cloudflare.o] Error 1
```

The fix can be either to move the loop variable declaration to the top of the function/context, or introduce -std=c99 in the Makefile.am. Your call.

**Comment by SimonPilkington** [comment]
Ah yes, good old C89. In my defence my newer GCC uses C99 by default. I'm going with using C99 (by adding AC_PROG_CC_C99 to configure.ac; I think that's correct) because I think that'll be the case for most people.

**Comment by SimonPilkington** [comment]
I'm wondering if `#define USERNAME_LEN                      50      /* chars */` will be a problem considering I need an email address and a zone name in the username. Should we extend this (to 128, say)?

**Comment by troglobit** [comment]
Awesome, and good idea to increase `USERNAME_LEN`, I've been thinking about doing that anyway. Go ahead!

**Comment by SimonPilkington** [comment]
Done. I also added some more length checking in my plugin, although frankly anyone who uses an email address or domain longer than 63 chars deserves all the segfaults they get.

**Comment by troglobit** [comment]
Great work with this one, thanks!

**Comment by SimonPilkington** [comment]
Happy to help. Don't forget to close #208.

**Comment by troglobit** [comment]
Ah, thanks for the reminder!

**Pull request merged**
